{% set name = "returns" %}
{% set version = "0.25.0" %}
{% set python_min = "3.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/returns-{{ version }}.tar.gz
  sha256: 1bf547311c0ade25435ce3bbe81642c325ea6b86beaf5d624cd410f0dee3ff50

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.9.0
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - typing_extensions >=4.0,<5.0

test:
  imports:
    - returns
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/dry-python/returns
  summary: Make your functions return something meaningful, typed, and safe!
  license: BSD-2-Clause
  license_file: LICENSE
  doc_url: https://returns.readthedocs.io
  description: |
    Brings functional programming to Python land by providing a bunch of
     primitives to write declarative business logic. Also enforces better
     architecture with fully typed with annotations and checked with mypy.
     This package is PEP561 compatible and adds emulated Higher Kinded Types
     support. It also provides type-safe interfaces to create your own data-types
     with enforced laws, and has a bunch of helpers for better composition. 

extra:
  recipe-maintainers:
    - thewchan
