{% set name = "returns" %}
{% set version = "0.20.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/returns-{{ version }}.tar.gz
  sha256: 90d21b03bbd9a6dc7d44317ca36e8080d2428679c74f2f15ec386816d09c4ece

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.6
  run:
    - python >=3.6
    - typing_extensions >=4.0

test:
  imports:
    - returns
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dry-python/returns
  summary: Make your functions return something meaningful, typed, and safe!
  license: BSD-2-Clause
  license_file: LICENSE
  doc_url: https://returns.readthedocs.io
  description: |
    Brings functional programming to Python land by providing a bunch of
     primitives to write declarative business logic. Also enforces better
     architecture with fully typed with annotations and checked with mypy.
     This package is PEP561 compatible and adds emulated Higher Kinded Types
     support. It also provides type-safe interfaces to create your own data-types
     with enforced laws, and has a bunch of helpers for better composition. 

extra:
  recipe-maintainers:
    - thewchan
